version: '3.8'

services:
  db:
    image: postgres:15
    container_name: boamassa-postgres
    restart: always
    environment:
      POSTGRES_USER: boamassauser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: boamassa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: boamassa-api
    restart: always
    ports:
      - "80:8080"
    environment:
      DATABASE_URL: postgres://boamassauser:admin@db:5432/boamassa
      NODE_ENV: development
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start"

volumes:
  postgres_data:
